# Generated by Django 4.2.5 on 2023-09-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_room_machinepart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_type',
        ),
    ]
