# Generated by Django 4.2.5 on 2023-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Imaging', 'Imaging'), ('Reading', 'Reading')], max_length=255),
        ),
    ]
