# Generated by Django 4.2.5 on 2023-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='examination',
            field=models.CharField(choices=[('CT', 'CT'), ('Radiology', 'Radiology'), ('Fluoroscopy', 'Fluoroscopy'), ('Dental', 'Dental'), ('Mammography', 'Mammography'), ('MRI', 'MRI')], max_length=255),
        ),
    ]
