# Generated by Django 4.2.5 on 2023-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_rename_type_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
