# Generated by Django 4.2.5 on 2023-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_alter_machine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
