# Generated by Django 4.2.5 on 2023-10-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_alter_room_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='machine',
            field=models.CharField(choices=[('CT Machine', 'CT Machine')], max_length=255),
        ),
    ]
