# Generated by Django 4.2.5 on 2023-09-28 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.TextField(max_length=500)),
                ('assigned_staff', models.CharField(choices=[('Allotey', 'Allotey Kwei'), ('Ama', 'Ama Maymani'), ('', ' '), ('', ' '), ('', ' ')], max_length=255)),
                ('room', models.CharField(blank=True, choices=[], max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[], max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=255)),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
