# Generated by Django 4.2.5 on 2023-10-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignment', '0002_alter_task_assigned_staff_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_staff',
            field=models.CharField(choices=[('Allotey', 'Allotey Kwei'), ('', ' '), ('', ' '), ('', ' '), ('Ama', 'Ama Maymani'), ('', ' ')], max_length=255),
        ),
    ]
