# Generated by Django 4.2.5 on 2023-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assignment', '0003_alter_task_assigned_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_staff',
            field=models.CharField(choices=[('Allotey', 'Allotey Kwei'), ('', ' '), ('', ' '), ('', ' '), ('', ' '), ('Ama', 'Ama Maymani')], max_length=255),
        ),
    ]
