# Generated by Django 4.2.5 on 2023-09-27 18:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('designated_staff_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.CharField(choices=[('Biostatistics', 'Biostatistics'), ('Nurse', 'Nurse'), ('Radiologist', 'Radiologist'), ('Radiographer', 'Radiographer'), ('Medical Physicist', 'Medical Physicist'), ('Biomedical Engineer', 'Biomedical Engineer'), ('Radiation Protection Officer', 'Radiation Protection Officer')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255, unique=True)),
                ('alternative_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('educational_level', models.CharField(choices=[], max_length=60)),
                ('work_experience', models.CharField(choices=[('<6M', 'Less than 6 months'), ('6M-1.5Y', '6 months - 1.5 years'), ('1.5Y-5Y', '1.5 - 5 years'), ('>5Y', 'More than 5 years')], max_length=255)),
                ('qualifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=270), size=None)),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
