# Generated by Django 4.2.5 on 2023-09-27 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designated_staff_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='educational_level',
            field=models.CharField(blank=True, choices=[], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_description',
            field=models.CharField(blank=True, choices=[('Biostatistics', 'Biostatistics'), ('Nurse', 'Nurse'), ('Radiologist', 'Radiologist'), ('Radiographer', 'Radiographer'), ('Medical Physicist', 'Medical Physicist'), ('Biomedical Engineer', 'Biomedical Engineer'), ('Radiation Protection Officer', 'Radiation Protection Officer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=270, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.CharField(blank=True, choices=[('<6M', 'Less than 6 months'), ('6M-1.5Y', '6 months - 1.5 years'), ('1.5Y-5Y', '1.5 - 5 years'), ('>5Y', 'More than 5 years')], max_length=255, null=True),
        ),
    ]
