# Generated by Django 4.2.5 on 2023-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='educational_level',
            field=models.CharField(blank=True, choices=[('BSc. Degree', 'BSc. Degree'), ('MSc. Degree', 'MSc. Degree'), ('Ph.D Degree', 'Ph.D Degree')], max_length=60, null=True),
        ),
    ]
