# Generated by Django 4.2.5 on 2023-09-21 16:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0003_rename_type_room_room_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('hospital_number', models.CharField(max_length=255)),
                ('patient_type', models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient', 'Outpatient')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('pregnant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('contact', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('note_date', models.DateTimeField()),
                ('note_title', models.CharField(max_length=255, null=True)),
                ('note', ckeditor.fields.RichTextField()),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient note',
                'verbose_name_plural': 'patient notes',
            },
        ),
        migrations.CreateModel(
            name='ImagingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('record_date', models.DateTimeField()),
                ('radiology_staff_id', models.CharField(max_length=255)),
                ('examination_repeat_type', models.CharField(choices=[('NRE', 'Non-Repeated Examination'), ('RE', 'Repeated Examination')], max_length=50)),
                ('setup_type', models.CharField(choices=[('AEC', 'AEC'), ('Manual', 'Manual')], max_length=50)),
                ('ctdi', models.CharField(default='N/A', max_length=255)),
                ('radiation_quality', models.CharField(default='N/A', max_length=255)),
                ('radiation_quantity', models.CharField(default='N/A', max_length=255)),
                ('current', models.CharField(default='N/A', max_length=255)),
                ('radiation_time', models.TimeField(null=True)),
                ('dose_area_product', models.CharField(default='N/A', max_length=255)),
                ('dose_length_product', models.CharField(default='N/A', max_length=255)),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('examination_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.room')),
                ('examination_type', models.ManyToManyField(to='general_setup.examinationtype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imaging record',
                'verbose_name_plural': 'imaging records',
            },
        ),
        migrations.CreateModel(
            name='ImageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('request_date', models.DateTimeField()),
                ('ward', models.CharField(max_length=255, null=True)),
                ('brief_clinical_history', models.TextField(max_length=500)),
                ('radiological_investigation_requested', models.TextField(max_length=500)),
                ('station', models.CharField(max_length=255)),
                ('radiology_serial_number', models.CharField(max_length=255)),
                ('previous_exams_details', models.TextField(max_length=500)),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('medical_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'image request',
                'verbose_name_plural': 'image requests',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('study_date', models.DateTimeField()),
                ('ward', models.CharField(max_length=255, null=True)),
                ('technique', ckeditor.fields.RichTextField()),
                ('findings', ckeditor.fields.RichTextField()),
                ('impressions', ckeditor.fields.RichTextField()),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('examination', models.ManyToManyField(to='general_setup.examinationtype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('requesting_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'diagnosis',
                'verbose_name_plural': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='AcquiredImageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('approval_date', models.DateTimeField(null=True)),
                ('radiology_staff_id', models.CharField(max_length=255)),
                ('image_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50)),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('imaging_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.imagingrecord')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acquired image status',
                'verbose_name_plural': 'acquired images statuses',
            },
        ),
    ]
