# Generated by Django 4.2.5 on 2023-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_imagerequestapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingrecord',
            name='ctdi',
            field=models.CharField(default='N/A', max_length=255, verbose_name='CTDI'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='current',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Current (mA)'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='dose_area_product',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Dose Area Product (DAP)'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='dose_length_product',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Dose Length Product (DLP)'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='radiation_quality',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Radiation Quality (KVP)'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='radiation_quantity',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Radiation Quantity (mAs)'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='radiation_time',
            field=models.DurationField(null=True, verbose_name='Time (sec)'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='note_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='patientnote',
            name='note_title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
