# Generated by Django 4.2.5 on 2023-10-07 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_imagingrecord_ctdi_alter_imagingrecord_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnote',
            name='note_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
