# Generated by Django 4.2.5 on 2023-10-12 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0007_alter_specificnote_end_time_of_exams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPreparationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('preparation_confirmation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, verbose_name='Has patient confirmed the receival of post preparation measures?')),
                ('injection_swelling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Swelling at injection site?')),
                ('staff_signature', models.CharField(max_length=255)),
                ('preparation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('activate_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'post preparation note',
                'verbose_name_plural': 'post preparation notes',
            },
        ),
        migrations.DeleteModel(
            name='PatientPostPreparationNote',
        ),
    ]
