# Generated by Django 4.2.5 on 2023-10-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_postpreparationnote_preparation_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingrecord',
            name='image_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquiredimagestatus',
            name='approval_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='acquiredimagestatus',
            name='imaging_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.imagingrecord'),
        ),
        migrations.AlterField(
            model_name='acquiredimagestatus',
            name='radiology_staff_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='examination_room',
            field=models.CharField(choices=[('Select Procedure', 'Select Procedure')], max_length=100),
        ),
    ]
