# Generated by Django 4.2.5 on 2023-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_imagingrecord_image_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingrecord',
            name='examination_room',
            field=models.CharField(choices=[('Select room', 'Select room')], max_length=100),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='radiation_time',
            field=models.CharField(default='N/A', max_length=50, null=True, verbose_name='Time (sec)'),
        ),
    ]
