# Generated by Django 4.2.5 on 2023-10-18 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_imagingrecord_examination_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagingrecord',
            name='image_status',
        ),
        migrations.AlterField(
            model_name='acquiredimagestatus',
            name='approval_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='acquiredimagestatus',
            name='imaging_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.imagingrecord'),
        ),
        migrations.AlterField(
            model_name='imagingrecord',
            name='examination_room',
            field=models.CharField(choices=[('Select room', 'Select room'), ('CT', 'Imaging CT')], max_length=100),
        ),
    ]
