# Generated by Django 4.2.5 on 2023-10-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_imagingrecord_image_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerejectreasons',
            name='acquired_image_status',
        ),
        migrations.AddField(
            model_name='acquiredimagestatus',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='imagerejectreasons',
            name='imaging_record',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='imagerejectreasons',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='acquiredimagestatus',
            name='imaging_record',
            field=models.UUIDField(null=True),
        ),
    ]
