# Generated by Django 4.2.5 on 2023-10-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_acquiredimagestatus_imaging_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerejectreasons',
            name='imaging_record',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='imagerejectreasons',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
