# Generated by Django 4.2.5 on 2023-10-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_imagerequestapproval_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequestapproval',
            name='image_request',
            field=models.UUIDField(),
        ),
    ]
